### ISSUE TITLE
Planning horizon YEAR logic

### ISSUE THREAD

**Issue by JulianGeis** [PyPSA/pypsa-ariadne#101]
**Adding existing capacities:** Atm we are adding existing capacities such that for planning horizon e.g. 2020 all existing capacities from 2020 until 2025 are added. This leads to existing capacities of e.g. solar PV of 81 GW (have been built until 2023) which are already present to the model in 2020. 
However we are setting co2 constraints and capacity expansion limits (Ausbauziele EE) according to the specific year, where they should be reached. This means, the model has capacities from the future to meet current co2 targets. E.g. it has 2023 solar PV capacities to meet 2020 co2 targets. 
Additionally we are implying limits on the capacity of e.g. solar expansion in 2020 and 2025. These limits apply for the specific year, which causes problems as the maximum targets are too low if the future capacity is added.

I suggest we align the logic such that planning horizon 2020 includes everything that is built until 2020. For 2025 this would mean the model has all capacities that are available until now and it uses the period 2020-2025 to optimize. Also the investment costs and capacity expansion would then apply to the period before the planning horizon.

Possible problems:
- one would have to check how the existing capacities are phased out; whether this fits the suggested logic or not

Changes to be made (probably more :)):
- change the grouping year logic such that only capacities until the year of the planning horizon are added
- check the phasing out of existing capacities in the myopic workflow

**Comment by lindnemi** [comment]
i think we basically need to undo some of the changes made here: https://github.com/PyPSA/pypsa-eur/pull/967
