### ISSUE TITLE
Missing Final Energy|Transportation|Liquids

### ISSUE THREAD

**Issue by toniseibold** [PyPSA/pypsa-ariadne#102]
![image](https://github.com/PyPSA/pypsa-ariadne/assets/153275395/126d9eec-5cc0-4841-bc64-85c73d65bd3a)

The variable `Final Energy|Liquids` is ~360 PJ lower compared to Remind. This is mostly due to the discrepancy between `Final Energy|Liquids|Transportation|` and reality.
The initial data in PyPSA-Eur (see `pop_weighted_energy_totals_s_{nodes}.csv`) is correct. The subcategories `total road` and `non electricity rail` add up to 618TWh = 2224.8 PJ. Together with the subcategories `domestic aviation = 10.5 TWh` and `domestic navigation = 3.4TWh` this adds to 2274 PJ which is only 40 PJ shy of what Remind is exporting.
The conversion steps to kilometers traveled and then to a oil load leads to a loss of 357 PJ in demand.

Real values e.g. taken from [DLR](https://www.dlr.de/de/aktuelles/nachrichten/daten-und-fakten/energieverbrauch-und-erneuerbare-energien-im-verkehr)

**Comment by lindnemi** [comment]
Up-to-date Primary Energy plot
![primary_energy](https://github.com/PyPSA/pypsa-ariadne/assets/56298440/1ae93569-c363-4035-925a-5273f60424da)

**Comment by lindnemi** [comment]
@lisazeyen pointed out that  `transport_ice_efficiency: 16.0712 # 1 MWh_oil = 16.0712 * 100 km` is set for LDV. This assumes too high efficiency for heavy duty. We could try to adjust the efficiency according to HDV/LDV share
