### ISSUE TITLE
missing bus for links in high spatial resolution

### ISSUE THREAD

**Issue by JulianGeis** [PyPSA/pypsa-ariadne#116]
- for 30 nodes for Germany urban central heat buses are missing
- ![image](https://github.com/PyPSA/pypsa-ariadne/assets/30044662/aa003f55-a260-47c0-9804-308974c57ae1)
- ![image](https://github.com/PyPSA/pypsa-ariadne/assets/30044662/87e7ed49-79ab-4a25-a499-0937ce4dbe6d)

**Comment by lindnemi** [comment]
i think there might be some nodes that just don't have district heating? @toniseibold @cpschau

**Comment by lindnemi** [comment]
fixed in pypsa-eur
