### ISSUE TITLE
Negative Hydrogen Demand in 2025 

### ISSUE THREAD

**Issue by toniseibold** [PyPSA/pypsa-ariadne#119]
Variables 
`Final Energy|Hydrogen` and `Final Energy|Industry excl Non-Energy Use|Hydrogen` are negative in 2025 with a value of `-0.38 PJ/yr`.
To work around this issue when executing the rule `plot_ariadne_variables` add to the function `side_by_side_plot()`
```
# check if there is a negative value in df
    if df.min().min() < 0:
        logger.warning(f"Negative values in {title} plot")
        df[df < 0] = 0
```

**Comment by lindnemi** [comment]
Negative values are hydrogen production from chloralkali process. Some of the plots can't deal with this, so its fine to overwrite with 0s
