### ISSUE TITLE
Industry Sector - Harmonizing with FORECAST

### ISSUE THREAD

**Issue by lindnemi** [PyPSA/pypsa-ariadne#121]
* too highly negative emissions in 2045 in industry (harmonise with FORECAST related to biomass, i.e. reduce biomass usage?)
* too much coal in 2045 (esp. Industry)

Following possibilities to harmonize FORECAST with PyPSA-Ariadne:

## Take the production volumes from FORECAST
This would leave the industry sector from PyPSA-Eur mostly untouched. The same sector ratios (energy demands per produced unit) would be used to calculate final energy demand in the industrial sector.
Problem: only small deviations between the scenarios from FORECAST since the production [Mt/yr] is expected to stay the same except for the Easy Ride and Low Demand scenarios.

![image](https://github.com/PyPSA/pypsa-ariadne/assets/153275395/1eb10697-18aa-45db-b97f-6e6b05f6b36b)

## Calculate FORECAST specific sector ratios for each year
The workflow in PyPSA-Eur would stay mostly the same, however the files `industry_sector_ratios_{planning_horizon}.csv` would change depending on the FORECAST results.
### Alternative a)
Stay very closely to FORECAST and specify even the source of gas (biomass vs. natural gas) and liquids (biomass vs. petroleum vs synfuels).
### Alternative b)
Give PyPSA-Ariadne more options to cover the demand by leaving it up to the model where e.g. the natural gas is coming from. 
The sectors do not match entirely between the JRC IDEES and the FORECAST model.

|PyPSA-Eur sector ratios | FORECAST |
|---|---|
|Electric arc | Steel |
|DRI + Electric arc | Steel |
| Integrated steelworks | Steel |
| HVC |
| HVC (mechanical recycling) |
| HVC (chemical recycling) |
| Ammonia | Chemicals |
| Chlorine | Chemicals |
| Methanol | Chemicals |
| Other chemicals | Chemicals |
| Pharmaceutical products etc. |
| Cement |Non-Metallic Minerals |
| Ceramics & other NMM | Non-Metallic Minerals|
| Glass production | Non-Metallic Minerals|
| Pulp production | Pulp and Paper|
| Paper production | Pulp and Paper|
| Printing and media reproduction | Pulp and Paper|
| Food, beverages and tobacco | Food and Tobacco|
| Alumina production | Non-Ferrous Metals|
| Aluminium - primary production | Non-Ferrous Metals |
| Aluminium - secondary production | Non-Ferrous Metals |
| Other non-ferrous metals | Non-Ferrous Metals|
| Transport Equipment | 
| Machinery Equipment | 
| Textiles and leather | 
| Wood and wood products | 
| Other Industrial Sectors | 

- [ ] FORECAST would need to report more variables

## Taking Demands from FORECAST
Most invasive way is taking the final energy demand `Final Energy|Industry|Carrier` from FORECAST and setting it as a demand in PyPSA-Ariadne. We would outsource the modelling of the industrial sector completely and would allow PyPSA-Ariadne only how to supply hydrogen, gas etc.
- [ ] What does FORECAST mean by `Final Energy|Industry|Heat`

**Comment by toniseibold** [comment]
After consideration we decided on:
- taking production volumes for Germany from FORECAST (which is already implemented) 
- taking our own assumption for the industry transformation
- [ ] take DRI ratio from FORECAST
- [ ] add config to vary the energy source for industry heat from currently only biomass to biomass, hydrogen and electricity (following scenario variations from FORECAST)
