### ISSUE TITLE
Process emissions are 0 in 2020

### ISSUE THREAD

**Issue by lindnemi** [PyPSA/pypsa-ariadne#124]
![Emissions-CO2-Industrial-Processes](https://github.com/PyPSA/pypsa-ariadne/assets/56298440/5893e35c-9220-41fa-b53c-53e0a93e96e6)

**Comment by lindnemi** [comment]
The issue occurs in in prepare_sector_network.

The industrial_demand.loc[nodes,"process emission"] seems to be 0 in 2020 in the loaded data, even though it is not 0 in the csv. It's very strange, there isn't even any preprocessing or year specific behaviour that could introduce the error.

**Comment by lindnemi** [comment]
ok i was looking at the wrong csv :/. 

The csv actually contains 0 process emissions for 2020....

**Comment by toniseibold** [comment]
Problem seems to occur while building `industrial_energy_Demand_elec_s_22_2020.csv`.
Tracing back to missing `process emission` and `process emission from feedstock` in `industry_sector_ratios_2020.csv` for
- `Integrated steelworks`
- `HVC`
- `Other chemicals`
- `Cement`
- `Ceramics & other NMM`
- `Glass production`
- `Aluminium - primary production`
- `Other non-ferrous metals`
Problem originates in `build_industry_sector_ratios_intermediate`
in the variable `today_sector_ratios` there is no index `process emission` and `process emission from feedstock` those only occur in `future_sector_ratios`.
The fraction of future sector ratios is 0 in 2020 and therefore, no emissions are taken into account.

**Comment by lindnemi** [comment]
Closed by [Excluding Emissions from Sector Ratios Development PyPSA/pypsa-eur#1154](https://github.com/PyPSA/pypsa-eur/pull/1154).
