### ISSUE TITLE
District Heating build-out

### ISSUE THREAD

**Issue by lindnemi** [PyPSA/pypsa-ariadne#136]
Our district heating build out is specified in config.yaml and stays the same for all scenarios:

```
sector:
  district_heating:
    potential: 0.4
    progress:
      2020: 0.0
      2025: 0.15
      2030: 0.3
      2036: 0.45
      2040: 0.6
      2045: 0.8
      2050: 1.0
```

Compared to the other models we have much less variations in DH

![Image](https://github.com/PyPSA/pypsa-ariadne/assets/56298440/e709899a-cbe9-4b5d-939f-5beca6feaf70)

Option A:
I think REMIND models the DH build-out endogenously. We could take over the DH potential and progress from their runs and only let PyPSA decide how to supply the heat. 

Option B:
We could also double check our assumption, find a source for the total DH potential, and specify different progress trajectories for each scenario in order to get more variation.

**Comment by lindnemi** [comment]
BMWK says

> Mit einem deutlich beschleunigten Ausbau der Wärmenetze soll sich die Anzahl der angeschlossenen Gebäude bis 2045 gegenüber heute in etwa verdreifachen, d.h. es sollen mittelfristig jährlich mindestens 100.000 Gebäude neu an Wärmenetze angeschlossen werden (https://www.bmwk.de/Redaktion/DE/Downloads/Energie/0612-erklaerung-fernwaeme-gipfel.pdf?__blob=publicationFile&v=8).

At the moment the DH share in urban areas is ~11.6% in the 2020 model. 

```
heat_demand = networks[-1].statistics.withdrawal(
        bus_carrier=["urban central heat","urban decentral heat"],**kwargs
    ).filter(like=region).groupby("carrier").sum().get(["urban central heat","urban decentral heat"])
heat_demand["urban central heat"] / heat_demand.sum()
```

And goes up to ~37.2% in 2045. That's a bit more than triple, and i am somewhat puzzled how it relates to the 0.4 specified in the config. But it's at least roughly the right order of magnitude.

To keep things simple I'd suggest to differentiate the scenarios as follows:

Zielerreichungs-Szenarien: Ausbau erreicht 35%
CurrentPolicies: Ausbau erreicht 20% (also die nächsten Jahre wird ausgebaut, dann stockt die Transformation)
Supply Focus: Ausbau erreicht wieder 35%
WorstCase: Wie CurrentPolicies (oder sogar nur schlechter mit 15%, "Infrastrukturausbau stockt").

@amosschle hatte noch vorgeschlagen den DH Ausbau an die waste_heat_usage_fraction zu koppeln. Finde ich eine sinnvolle Annahme, Frage wäre dann nur welche Zahlen wir dafür annehmen.

**Comment by lindnemi** [comment]
@nworbmot @cpschau Maybe you have some useful input

**Comment by lindnemi** [comment]
at the moment district heat share for Germany in 2020 is 0.077 [specified in districit_heat_share.csv]

Where does this number come from? And what exactly does it mean?

Since the BMWK aims for a tripling by 2045, maybe we could just triple that number to arrive at a DH potential?

**Comment by lindnemi** [comment]
Number comes from `build_district_heat_share` and is a conservative estimate of existing capacities. 0.077 is the fraction of total heat demand. The fraction of urban heat demand in DE would be around 0.1 -> tripling that we arrive at 0.3.

**Comment by nworbmot** [comment]
Sounds good to me!

**Comment by amosschle** [comment]
I'm still a bit puzzled by the DH share of 7.7%. According to BDEW, it's 14.2% (including Nahwärme).

**Comment by cpschau** [comment]
The district_heat_share.csv of the PyPSA-Eur master branch indicates 13.8% for Germany (https://github.com/PyPSA/pypsa-eur/blob/master/data/district_heat_share.csv).

Statistics about the heat sector should be carefully examined to determine whether they refer to the entire heat demand, including process heat, or just building heat. In the case of Germany process heat contributes another 600 TWh FED (UBA 2021: https://www.umweltbundesamt.de/daten/energie/energieverbrauch-fuer-fossile-erneuerbare-waerme).

**Comment by lindnemi** [comment]
I reduced the potential to 0.3, and for Current Policies and Worst Case scenarios to 0.1

59333db0059a7ac4a72aa8814c649774528bf5de
