### ISSUE TITLE
Allow H2 retrofit of gas pipelines

### ISSUE THREAD

**Issue by lindnemi** [PyPSA/pypsa-ariadne#138]
- [x] It's false in config.default.yaml but should be true
- [x] Test run with H2_Kernnetz enabled, to make sure it work together

**Comment by toniseibold** [comment]
I checked the workflow:
regardless of the `config["sector"]["gas_network"]`, the  rules `build_gas_network`, `build_gas_input_locations` etc. are executed.
The results of the rules `cluster_gas_network` and `build_gas_input_locations` are all input to the `prepare_sector_network` rule.
There in the function `add_storage_and_grids(n, costs)`, the following if/else statements are taken into account:
With the config of pypsa-ariadne (`H2_retrofit` and `~gas_network`):
- gas pipelines are not added but links with a p_nom of 0 and p_nom_max of `H2_retrofit_capacity_per_CH4` times the gas pipelines
In `solve_network` not boundary condition is then set for the retrofit of gas to hydrogen pipelines
The prenetwork only contains links for retrofitting existing gas pipelines
```
n.links[n.links.carrier == "H2 pipeline retrofitted"]
``` 

![Image](https://github.com/user-attachments/assets/9a6ad3a7-a30f-46ab-9f8c-a328230a42f7)

and gas pipelines are not existing
```
n.links[n.links.carrier == "gas pipeline"]
``` 


![Image](https://github.com/user-attachments/assets/14451cbf-6b19-4c82-8bd5-a7869374cc2b)

**Comment by toniseibold** [comment]
With this PR in pypsa-eur the Kernnetz should now work with H2_retrofit and without a gas network
https://github.com/PyPSA/pypsa-eur/pull/1258
