### ISSUE TITLE
Validator issue

### ISSUE THREAD

**Issue by lindnemi** [PyPSA/pypsa-ariadne#162]
- [x] compare all variables in `ariadne/exported_variables_full.xlsx`, report deviations and if these cross a certain threshold post the corresponding plot from `ariadne_all` to the PR
- [x] somehow record the output from the log files and make it available if a job fails.
- [ ] Separate CI for every release: Runs with higher resolution and makes the results persistent, e.g. uploading them to a cloud folder
- [ ] Snakemake benchmarks
- [ ] Handle changed environments

**Comment by lkstrp** [comment]
Moved to https://github.com/lkstrp/pypsa-validator/issues/10
