### ISSUE TITLE
Fix electricity validation for 2020

### ISSUE THREAD

**Issue by lindnemi** [PyPSA/pypsa-ariadne#186]
From the latest 3H run (Elec scenario)
![Image](https://github.com/user-attachments/assets/a4b3188d-abbc-4c6f-99d3-bc5cf1dceada)

- First thing would be to fix nuclear not being used. Tom thinks it might be a bug because it is relatively cheap

**Comment by lindnemi** [comment]
The biomass must_run has been turned off, because we now declare all small Bioenergy plants as biogas and those would be the ones that run all the time. However, the availability of biogas is not aligned with the location of the biogas plants we get form this heuristic. So must_run for these can be set to maximum of 0.25 whereas it should ideally be close to 0.5

**Comment by JulianGeis** [comment]
![image](https://github.com/user-attachments/assets/891448db-9920-415d-a981-179fd5369cb7)
