### ISSUE TITLE
Fix spurious offshore capacity in Hessen

### ISSUE THREAD

**Issue by lindnemi** [PyPSA/pypsa-ariadne#198]
Apparently we have a offshore wind farm in Hessen. I suspect a bug in the input data

![image](https://github.com/user-attachments/assets/44c5ada2-9c98-4492-8831-d7117feb9fa6)

**Comment by toniseibold** [comment]
This seems to be a bigger issue:
In `cluster_network` the following code gives a visualization of the problem:
```
regions_onshore = gpd.read_file("/path/to/resources/regions_onshore_elec_s.geojson").set_index("name")
n = pypsa.Network("path/to/resources/networks/elec_s.nc")
regions_onshore.explore(column=n.generators.query("carrier=='offwind-ac'").groupby("bus").p_nom_max.sum().reindex(regions_onshore.index))
``` 
![Image](https://github.com/user-attachments/assets/52d5186c-9d07-4ddc-8b49-cf8610a91fe1)

**Comment by lindnemi** [comment]
This problem will be fixed when merging master into ariadne2. Question is when we find the time to do that....

**Comment by lindnemi** [comment]
master merged, plot looking good
![Image](https://github.com/user-attachments/assets/6989d49e-cc3c-4424-b359-9c39242667a1)
