### ISSUE TITLE
mock_snakemake not working anymore

### ISSUE THREAD

**Issue by toniseibold** [PyPSA/pypsa-ariadne#246]
Since the latest merge of pypsa-eur master into ariadne2 mock_snakemake is not working anymore
The problem arises in the `_helpers`
https://github.com/PyPSA/pypsa-eur/blob/d43ce53c85b6ce114f0c3013a49450b50e8ca5bc/scripts/_helpers.py#L456
compared to 
https://github.com/PyPSA/pypsa-eur/blob/0026b0f33bb37ebbec1b0433f1b9ccd9cc208e94/scripts/_helpers.py#L448C5-L448C50
Changing just this line makes it work again, however one should ensure that we don't run into more problems from the latest merge.

**Comment by lindnemi** [comment]
Lukas said you have to install pypsa 0.31 in your environment (which makes a lot of sense, since this was the point of the update)

**Comment by lkstrp** [comment]
Not working with `pypsa<0.31`. `pypsa>=0.31` which is the now pinned version in pypsa-eur will work. `<0.31` will fail anyways because of the `n.add` changes in pypsa-eur.
