### ISSUE TITLE
Bug Restricting Capacities and Volumes

### ISSUE THREAD

**Issue by toniseibold** [PyPSA/pypsa-ariadne#270]
In `additional_functionality` the following constraints are not exactly working as intended.
- FT production limit
- capacity limits for electrolysis in Germany
since the limit is set on the capacity of `bus0` which in the case of FT production is hydrogen and in case of electrolysis is electricity. Dividing the capacity by the `efficiency` should solve the bug.

**Comment by lindnemi** [comment]
closed by #278 and direct follow-up commits to main
