### ISSUE TITLE
Restricting Installed Capacities Instead of Production Volumes

### ISSUE THREAD

**Issue by toniseibold** [PyPSA/pypsa-ariadne#271]
The ' FT_production_limit` might lead to performance issues during the optimization.
To counteract, we should add a capacity limit for FT and MeOH. So far we observe for 2045 balanced scenario
- FT production volume of 149.3 GWh at a installed capacity of 1.9 GW which translates to 78.1 full load hours
- MeOH production volume of 12.5 TWh at a installed capacity of 9.8 GW which translates to 1280 full load hours

**Comment by lindnemi** [comment]
closed by #278
