### ISSUE TITLE
New database connection

### ISSUE THREAD

**Issue by toniseibold** [PyPSA/pypsa-ariadne#30]
Wir haben für die 2. Projektphase eine neue interne Instanz der Szenarien-Datenbank bei IIASA angelegt: https://data.ene.iiasa.ac.at/ariadne2-intern/#/workspaces.

In der neuen DB sind die folgenden Szenarien-Slots für den Upload der neuen Szenarien verfügbar:

    CurrentPolicies
    KN2045_Bal_v4
    KN2045_Elec_v4
    KN2045_H2_v4
    KN2045plus_LowDemand
    KN2045plus_EasyRide
    KN2045minus_WorstCase
    KN2045minus_SupplyFocus

CurrentPolicies als bessere Bezeichnung für das Trend-Szenario, KN2045plus steht für mögliche Übererfüllung der Ziele, KN2045minus für eine mögliche Zielverfehlung.

Es bestehen die bisherigen Berechtigungen zum Up- und Download, ebenso gilt die Nutzungsvereinbarung, der alle zugriffsberechtigten Teams zugestimmt haben (zur Sicherheit noch einmal im Anhang). Insbesondere sind alle geteilten Szenarien-Ergebnisse nur intern zu verwenden und vertraulich zu behandeln.
Wie schon in Projektphase 1, wird es demnächst wieder zusätzlich eine öffentliche Instanz geben.

Viele Grüße,
Frederike

**Comment by lindnemi** [comment]
Closed by #36
