### ISSUE TITLE
Missing Biofuels

### ISSUE THREAD

**Issue by toniseibold** [PyPSA/pypsa-ariadne#43]
## Problem
- `Final Energy|Transportation|Liquids|Biomass` in ariadne database
- We don't model biofuels yet

![image](https://github.com/PyPSA/pypsa-ariadne/assets/153275395/0e5cc5b9-aa11-461b-9312-92b0b5edfcd9)
![image](https://github.com/PyPSA/pypsa-ariadne/assets/153275395/85531427-c3c4-41e9-93b2-dc8279674a8d)
![image](https://github.com/PyPSA/pypsa-ariadne/assets/153275395/3bcf05ad-d345-4889-b6a7-006ca0f7a29c)

- rest is used for (n)avi(g)ation

## Implemention proposal:
- adding configuration of 
	- `[sector][land_transport_ice_biofuel_share]`
	- `[sector][shipping_biofuel_share]`
	- `[sector][aviation_biofuel_share]`
- `prepare_sector_network.py`
	- `add_land_transport()`, `add_industry()`
	- adding `buses`, `loads` and `links`
	- biofuels have unavoidable CO2 emissions (approx. 70 % compared to fossil fuels)

## Comment
We have to add unsustainable biomass especially for 2020. Exogenously forcing a phase out or adding CO2 emissions for that.
Maybe add a cheaper source of biomass and phase out its potential.

**Comment by cpschau** [comment]
Closed by https://github.com/PyPSA/pypsa-eur/pull/1139
