### ISSUE TITLE
Refinements of Wasserstoff-Kernnetz

### ISSUE THREAD

**Issue by fneum** [PyPSA/pypsa-ariadne#9]
- [x] check overlap of Kernnetz with IPCEI projects (I think there is code from Ammar)
- [x] Implement that those pipelines from Kernnetz marked as retrofitted gas pipelines remove corresponding gas pipeline capacity
- [x] consider `build_year` when adding capacities: `custom_pipes.query("build_year <= @investment_year", inplace=True)`
- [x] **until 2030:** only assume that pipelines from Kernnetz are built (`p_nom_extendable=False`, via `p_nom` taking into account build years (i.e. less in 2025 than in 2030)). Pipelines outside of Germany should be extendable because we don't have data.
- [x] **after 2030:** Set also H2 pipelines in Germany to `p_nom_extendable=True` but with Kernnetz capacities as `p_nom_min` (as implemented now).

**Comment by JulianGeis** [comment]
The overlap with the ipcei pipelines lokks good:
IPCEI:
![image](https://github.com/PyPSA/pypsa-ariadne/assets/30044662/9b86252f-b902-4fb4-ad9e-c90c22537252)

Model:
![image](https://github.com/PyPSA/pypsa-ariadne/assets/30044662/8494ecb5-f878-4947-a20d-287ba5343936)

**Comment by JulianGeis** [comment]
Two questions concerning the implementation of the reduction of the corresponding gas pipeline capacity if it is retrofitted for H2: If I see it correctly, the gas pipelines are implemented such that they are partially bidirectional and partially unidirectional. The kernnetz is implemented completely bidirectional. 

1: So I would remove the capacity from the sum of the uni- and bidirectional gas pipes capacity and not from every existing pipeline? 
2: How comes that, the reversed pipelines can have a smaller p_nom that the corresponding bidirectional pipeline? 

![image](https://github.com/PyPSA/pypsa-ariadne/assets/30044662/02744754-4550-4eb4-9d1c-888adc05d215)

**Comment by JulianGeis** [comment]
Tasks of refinement are build in:
1. If kernnetz pipeline is build in period, the corresponding gas pipeline capacity is removed if it exists
2. build_year is considered
3. until 2030 H2 pipes in Germany are not extendable, however kernnetz exists
4. from 2030 all H2 pipelines are extedable, The kernnetz capacities are not implemented as p_nom_min, but as additional lines which is not extendable.

What I checked:
# checklist
- kernnetz: check with 
    2020: no kernnetz
    2030: correctly builds 20 pipes (with reversed)
    2040: correctly builds 10 additional pipes (with reversed)
    2050: no mor pipes (already completely build)
    code: n.links[n.links.index.str.contains("kernnetz")]

- reduction of gas network:
    2020: no difference in gas pipelines between prenetworks brownfield and prenetworks-final
    2030: 614 GW removed of 639 GW possible removed
    2040: 65 GW removed from possible 175 GW
    2050: no more removal
    code: n_bf.links.loc[(n_bf.links.carrier == "gas pipeline"), :].p_nom.sum() - n_f.links.loc[(n_f.links.carrier == "gas pipeline"), :].p_nom.sum()

- p_nom max of prenetworks-final is roughly such an amount lower as the wkn in the period: 
    2020: p_nom max is 282 GW lower in final, whole reduction would have been 489 GW if you account for bidirectional pipes (reason for difference is that there is no retrofitting potential is some pipes of the gas network where it should be) 
    2030: same as year before
    2040: same
    2050: same

- plots of kernnetz:
- 2020: no kernnetz
- 2030:
![image](https://github.com/PyPSA/pypsa-ariadne/assets/30044662/407d49d1-8a12-4a9e-a504-f578c082afd4)
2040:
![image](https://github.com/PyPSA/pypsa-ariadne/assets/30044662/4476e554-d6b9-4e0f-a9fe-92f2335655d4)
2050: same as 2040

- code :
```
n_f.links.bus0 = n_f.links.bus0.str[:-3]
n_f.links.bus1 = n_f.links.bus1.str[:-3]

# 2030
import cartopy.crs as ccrs
import pandas as pd

fig, ax = plt.subplots(1, 1, figsize=(20,20), subplot_kw={"projection":ccrs.PlateCarree()})
n_f.links = n_f.links.loc[(n_f.links.carrier == "H2 pipeline") & (n_f.links.index.str.contains("kernnetz")), :]

n_f.plot(ax=ax, line_widths=0, link_widths=n_f.links.p_nom/5e3) 
```

- the reduction of retrofitted and gas pipeline capacity is applied don the right lines
- To run the model with H2 retrofit those fixes have to be made to pypsa-eur submoduls branch:
- https://github.com/daniel-rdt/pypsa-eur/blame/44d9337b2e826aaa25b285784b3efa960bdb96e1/scripts/plot_network.py#L325-L337
- https://github.com/daniel-rdt/pypsa-eur/blame/44d9337b2e826aaa25b285784b3efa960bdb96e1/scripts/plot_network.py#L263-L268
